# Generated by Django 2.1.3 on 2019-02-09 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ndmu', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SliderImages',
        ),
    ]
