# Generated by Django 2.1.3 on 2018-12-20 07:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('whatsnew', '0002_auto_20181220_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsnew',
            name='date_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
