# Generated by Django 2.1.3 on 2018-12-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsnew', '0003_whatsnew_date_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsnew',
            name='whatsnew_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
